import { Exercise } from "../types/exercise";

export const EXERCISES: Exercise[] = [
  {
    id: "patella-setting",
    name: "パテラセッティング",
    nameEn: "Quad Sets",
    target: "大腿四頭筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 20,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description: "膝裏にタオルを置き、膝裏でタオルを押し潰すように力を入れます",
    keyPoints: [
      "膝裏でタオルをしっかり押す",
      "太ももの前に力が入ることを確認",
      "5秒間キープしてゆっくり力を抜く",
    ],
  },
  {
    id: "slr",
    name: "SLR（下肢伸展挙上）",
    nameEn: "Straight Leg Raise",
    target: "大腿四頭筋・腸腰筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "膝を伸ばしたまま足を持ち上げ、ゆっくり降ろします",
    keyPoints: [
      "膝をしっかり伸ばしたまま上げる",
      "反対側の膝は曲げておく",
      "30〜45度まで上げて5秒キープ",
    ],
  },
  {
    id: "bridge",
    name: "ブリッジ（ヒップリフト）",
    nameEn: "Hip Lift / Bridge",
    target: "大殿筋・ハムストリングス",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "両膝を曲げてお尻を持ち上げ、肩から膝が一直線になるようにします",
    keyPoints: [
      "お尻をしっかり締めて持ち上げる",
      "肩〜膝が一直線になるまで上げる",
      "腰を反らしすぎない",
    ],
  },
  {
    id: "clamshell",
    name: "クラムシェル",
    nameEn: "Clamshell",
    target: "中殿筋・外旋筋群",
    posture: "側臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "横向きに寝て膝を曲げ、足をつけたまま上の膝を開きます",
    keyPoints: [
      "両足はつけたまま膝だけ開く",
      "骨盤が後ろに倒れないようにする",
      "お尻の横に力が入ることを確認",
    ],
  },
  {
    id: "squat",
    name: "スクワット",
    nameEn: "Squat",
    target: "大腿四頭筋・大殿筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子の背に手を添え、ゆっくり腰を落として戻します",
    keyPoints: [
      "膝がつま先より前に出すぎない",
      "椅子や壁に手を添えて安全に",
      "息を止めずにゆっくり行う",
    ],
  },
  {
    id: "calf-raise",
    name: "カーフレイズ",
    nameEn: "Calf Raise",
    target: "下腿三頭筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "壁や椅子に手を添えて、つま先立ちになりゆっくり戻します",
    keyPoints: [
      "かかとをできるだけ高く上げる",
      "体はまっすぐに保つ",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "draw-in",
    name: "ドローイン",
    nameEn: "Abdominal Drawing-in",
    target: "腹横筋",
    posture: "臥位",
    category: "体幹",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "息を吐きながらおへそを背骨に引き寄せるようにお腹を凹ませます",
    keyPoints: [
      "息を吐きながらお腹を凹ませる",
      "10秒キープして自然に呼吸",
      "腰が床から浮かないようにする",
    ],
  },
  {
    id: "seated-knee-ext",
    name: "座位での膝伸展",
    nameEn: "Seated Knee Extension",
    target: "大腿四頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "椅子に座り、片脚の膝をまっすぐ伸ばして持ち上げます",
    keyPoints: [
      "つま先を天井に向ける",
      "背筋を伸ばして座る",
      "5秒キープしてゆっくり下ろす",
    ],
  },
  {
    id: "scapular-retraction",
    name: "肩甲骨内転運動",
    nameEn: "Scapular Retraction",
    target: "菱形筋・僧帽筋中部",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "胸を張り、肩甲骨を背骨に向かって寄せます",
    keyPoints: [
      "肩甲骨を中央に寄せるイメージ",
      "肩は上がらないようにする",
      "顎を引いて良い姿勢で行う",
    ],
  },
  {
    id: "wall-pushup",
    name: "ウォールプッシュアップ",
    nameEn: "Wall Push-Up",
    target: "大胸筋・上腕三頭筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁に両手をつき、肘を曲げて体を壁に近づけ、押し戻します",
    keyPoints: [
      "壁から腕一本分離れて立つ",
      "体を一直線に保つ",
      "肘を曲げてゆっくり近づく",
    ],
  },
];
