import { Exercise } from "../types/exercise";

export const EXERCISES: Exercise[] = [
  {
    id: "patella-setting",
    name: "パテラセッティング",
    nameEn: "Quad Sets",
    target: "大腿四頭筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 20,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description: "膝裏にタオルを置き、膝裏でタオルを押し潰すように力を入れます",
    keyPoints: [
      "膝裏でタオルをしっかり押す",
      "太ももの前に力が入ることを確認",
      "5秒間キープしてゆっくり力を抜く",
    ],
  },
  {
    id: "slr",
    name: "SLR（下肢伸展挙上）",
    nameEn: "Straight Leg Raise",
    target: "大腿四頭筋・腸腰筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "膝を伸ばしたまま足を持ち上げ、ゆっくり降ろします",
    keyPoints: [
      "膝をしっかり伸ばしたまま上げる",
      "反対側の膝は曲げておく",
      "30〜45度まで上げて5秒キープ",
    ],
  },
  {
    id: "bridge",
    name: "ブリッジ（ヒップリフト）",
    nameEn: "Hip Lift / Bridge",
    target: "大殿筋・ハムストリングス",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "両膝を曲げてお尻を持ち上げ、肩から膝が一直線になるようにします",
    keyPoints: [
      "お尻をしっかり締めて持ち上げる",
      "肩〜膝が一直線になるまで上げる",
      "腰を反らしすぎない",
    ],
  },
  {
    id: "clamshell",
    name: "クラムシェル",
    nameEn: "Clamshell",
    target: "中殿筋・外旋筋群",
    posture: "側臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "横向きに寝て膝を曲げ、足をつけたまま上の膝を開きます",
    keyPoints: [
      "両足はつけたまま膝だけ開く",
      "骨盤が後ろに倒れないようにする",
      "お尻の横に力が入ることを確認",
    ],
  },
  {
    id: "squat",
    name: "スクワット",
    nameEn: "Squat",
    target: "大腿四頭筋・大殿筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子の背に手を添え、ゆっくり腰を落として戻します",
    keyPoints: [
      "膝がつま先より前に出すぎない",
      "椅子や壁に手を添えて安全に",
      "息を止めずにゆっくり行う",
    ],
  },
  {
    id: "calf-raise",
    name: "カーフレイズ",
    nameEn: "Calf Raise",
    target: "下腿三頭筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "壁や椅子に手を添えて、つま先立ちになりゆっくり戻します",
    keyPoints: [
      "かかとをできるだけ高く上げる",
      "体はまっすぐに保つ",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "draw-in",
    name: "ドローイン",
    nameEn: "Abdominal Drawing-in",
    target: "腹横筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "息を吐きながらおへそを背骨に引き寄せるようにお腹を凹ませます",
    keyPoints: [
      "息を吐きながらお腹を凹ませる",
      "10秒キープして自然に呼吸",
      "腰が床から浮かないようにする",
    ],
  },
  {
    id: "seated-knee-ext",
    name: "座位での膝伸展",
    nameEn: "Seated Knee Extension",
    target: "大腿四頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "椅子に座り、片脚の膝をまっすぐ伸ばして持ち上げます",
    keyPoints: [
      "つま先を天井に向ける",
      "背筋を伸ばして座る",
      "5秒キープしてゆっくり下ろす",
    ],
  },
  {
    id: "scapular-retraction",
    name: "肩甲骨内転運動",
    nameEn: "Scapular Retraction",
    target: "菱形筋・僧帽筋中部",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "胸を張り、肩甲骨を背骨に向かって寄せます",
    keyPoints: [
      "肩甲骨を中央に寄せるイメージ",
      "肩は上がらないようにする",
      "顎を引いて良い姿勢で行う",
    ],
  },
  {
    id: "wall-pushup",
    name: "ウォールプッシュアップ",
    nameEn: "Wall Push-Up",
    target: "大胸筋・上腕三頭筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁に両手をつき、肘を曲げて体を壁に近づけ、押し戻します",
    keyPoints: [
      "壁から腕一本分離れて立つ",
      "体を一直線に保つ",
      "肘を曲げてゆっくり近づく",
    ],
  },
  // ── 追加12種 ──
  {
    id: "bird-dog",
    name: "ダイアゴナル（バードドッグ）",
    nameEn: "Bird Dog",
    target: "脊柱起立筋・多裂筋",
    posture: "四つ這い",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "四つ這いで対側の手と脚をまっすぐ伸ばし、体幹を安定させます",
    keyPoints: [
      "右手と左脚（対側）を同時に伸ばす",
      "腰が反ったり傾いたりしないように",
      "5秒キープしてゆっくり戻す",
    ],
  },
  {
    id: "plank",
    name: "プランク",
    nameEn: "Plank",
    target: "腹横筋・腹直筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "前腕とつま先で体を支え、頭から踵まで一直線を保ちます",
    keyPoints: [
      "肘は肩の真下に置く",
      "お尻が上がったり下がったりしない",
      "呼吸を止めずにキープ",
    ],
  },
  {
    id: "sit-up",
    name: "シットアップ（腹筋）",
    nameEn: "Sit-Up",
    target: "腹直筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "仰向けで両膝を曲げ、肩甲骨が浮く程度に上体を起こします",
    keyPoints: [
      "両手は胸の前で交差する",
      "反動を使わずゆっくり起き上がる",
      "腰が痛い場合は中止する",
    ],
  },
  {
    id: "trunk-rotation",
    name: "トランクローテーション",
    nameEn: "Trunk Rotation",
    target: "腹斜筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、両手を胸の前で組んで上半身をゆっくり左右に回旋します",
    keyPoints: [
      "骨盤は正面を向いたまま",
      "背筋を伸ばして行う",
      "痛みのない範囲でゆっくり回す",
    ],
  },
  {
    id: "shoulder-flexion",
    name: "肩関節屈曲挙上",
    nameEn: "Shoulder Flexion",
    target: "三角筋前部",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "椅子に座り、腕をまっすぐ前方からバンザイ方向に挙げます",
    keyPoints: [
      "肘を伸ばしたまま挙げる",
      "痛みのない範囲で行う",
      "肩をすくめないように注意",
    ],
  },
  {
    id: "shoulder-abduction",
    name: "肩関節外転挙上",
    nameEn: "Shoulder Abduction",
    target: "三角筋中部",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "椅子に座り、腕を体の横方向にゆっくり挙げます",
    keyPoints: [
      "肘を伸ばしたまま横に挙げる",
      "肩の高さまで（約90度）を目安に",
      "肩をすくめないように注意",
    ],
  },
  {
    id: "shoulder-external-rotation",
    name: "肩外旋運動",
    nameEn: "Shoulder External Rotation",
    target: "棘下筋・小円筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "脇を締めて肘を90度に曲げ、セラバンドを持って手を外側に開きます",
    keyPoints: [
      "脇をしっかり締めたまま行う",
      "肘の位置を動かさない",
      "ゆっくり戻す（戻す時も筋力を使う）",
    ],
  },
  {
    id: "hand-grip",
    name: "グーパー運動",
    nameEn: "Hand Grip Exercise",
    target: "前腕屈筋群・伸筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 20,
    defaultSets: 3,
    description:
      "手をしっかり握って（グー）、大きく開く（パー）を繰り返します",
    keyPoints: [
      "指を大きく開いてしっかりパーにする",
      "握る時もしっかり力を入れる",
      "むくみがある場合は手を挙げて行う",
    ],
  },
  {
    id: "hip-abduction",
    name: "ヒップアブダクション（側臥位）",
    nameEn: "Hip Abduction",
    target: "中殿筋",
    posture: "側臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "横向きに寝て、上側の脚を膝を伸ばしたまま持ち上げます",
    keyPoints: [
      "膝をまっすぐ伸ばしたまま上げる",
      "骨盤が後ろに倒れないようにする",
      "お尻の横に力が入ることを確認",
    ],
  },
  {
    id: "hamstring-curl",
    name: "ハムストリングスカール",
    nameEn: "Hamstring Curl",
    target: "ハムストリングス",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "うつ伏せで片脚の膝を曲げ、踵をお尻に近づけます",
    keyPoints: [
      "太ももの裏に力が入ることを確認",
      "骨盤が浮かないようにする",
      "ゆっくり曲げてゆっくり戻す",
    ],
  },
  {
    id: "tandem-stance",
    name: "タンデム立位（継ぎ足）",
    nameEn: "Tandem Stance",
    target: "バランス",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 15,
    description:
      "片足のつま先にもう片足の踵をつけて一直線に立ち、バランスを保ちます",
    keyPoints: [
      "必ず壁や椅子の近くで行う",
      "ふらつく場合は手を添える",
      "視線は正面のやや下を見る",
    ],
  },
  {
    id: "step-up",
    name: "ステップ運動（踏み台昇降）",
    nameEn: "Step-Up",
    target: "大腿四頭筋・大殿筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "低い踏み台や階段の段差を使って、昇り降りを繰り返します",
    keyPoints: [
      "手すりや壁に手を添えて安全に",
      "膝がつま先より前に出すぎない",
      "10〜15cmの低い段差から始める",
    ],
  },
  // ── Batch 3: ストレッチ系 ──
  {
    id: "hamstring-stretch",
    name: "ハムストリングスストレッチ",
    nameEn: "Hamstring Stretch",
    target: "ハムストリングス",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "椅子に浅く座り、片脚を前に伸ばして背筋を保ったまま上体を前に倒します",
    keyPoints: [
      "膝をしっかり伸ばしたまま行う",
      "背中を丸めずに股関節から倒す",
      "太もも裏に伸びを感じたら20秒キープ",
    ],
  },
  {
    id: "quad-stretch",
    name: "大腿四頭筋ストレッチ",
    nameEn: "Quadriceps Stretch",
    target: "大腿四頭筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "壁に手を添えて立ち、片手で同側の足首を持って踵をお尻に引き寄せます",
    keyPoints: [
      "膝を閉じたまま行う",
      "体はまっすぐに保つ",
      "太もも前面に伸びを感じたら20秒キープ",
    ],
  },
  {
    id: "calf-stretch",
    name: "下腿三頭筋ストレッチ",
    nameEn: "Calf Stretch",
    target: "下腿三頭筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "壁に手をつき、片脚を後ろに引いて踵を床につけたままふくらはぎを伸ばします",
    keyPoints: [
      "後ろ脚の膝はまっすぐ伸ばす",
      "踵を床から浮かさない",
      "ふくらはぎに伸びを感じたら20秒キープ",
    ],
  },
  {
    id: "hip-flexor-stretch",
    name: "股関節屈筋ストレッチ",
    nameEn: "Hip Flexor Stretch",
    target: "腸腰筋・大腿直筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "片膝立ちで背筋を伸ばし、重心を前方に移動して股関節前面を伸ばします",
    keyPoints: [
      "背筋をまっすぐ保つ",
      "後ろ脚の股関節前面に伸びを感じる",
      "膝が痛い場合はタオルを敷く",
    ],
  },
  {
    id: "piriformis-stretch",
    name: "梨状筋ストレッチ",
    nameEn: "Piriformis Stretch",
    target: "梨状筋・深層外旋六筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "椅子に座り、片方の足首を反対の膝に乗せて上体を前に倒します",
    keyPoints: [
      "背中を丸めずに股関節から倒す",
      "お尻の奥に伸びを感じたらキープ",
      "痛みが強い場合は無理をしない",
    ],
  },
  {
    id: "itb-stretch",
    name: "腸脛靭帯ストレッチ",
    nameEn: "IT Band Stretch",
    target: "腸脛靭帯・大腿筋膜張筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "壁に手を添え、ストレッチ側の脚を後ろに交差させて腰を横に押し出します",
    keyPoints: [
      "脚を交差させて体をC字カーブに",
      "太ももの外側に伸びを感じる",
      "壁に手を添えてバランスを取る",
    ],
  },
  {
    id: "shoulder-flexion-stretch",
    name: "肩関節屈曲ストレッチ",
    nameEn: "Shoulder Flexion Stretch",
    target: "大胸筋・三角筋前部",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "壁に手をつき、体を前方に沈めて肩の前面を伸ばします",
    keyPoints: [
      "手は肩より高い位置で壁につける",
      "体をゆっくり前方に沈める",
      "肩の前面に伸びを感じたらキープ",
    ],
  },
  {
    id: "shoulder-er-stretch",
    name: "肩関節外旋ストレッチ",
    nameEn: "Shoulder External Rotation Stretch",
    target: "肩甲下筋・大胸筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "壁の角で肘を90度に曲げて前腕を壁につけ、体を反対方向に回旋します",
    keyPoints: [
      "肘は肩の高さに保つ",
      "ゆっくり体を回旋する",
      "肩の前面に伸びを感じたらキープ",
    ],
  },
  {
    id: "shoulder-ha-stretch",
    name: "肩関節水平内転ストレッチ",
    nameEn: "Shoulder Horizontal Adduction Stretch",
    target: "三角筋後部・棘下筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "片腕を胸の前で水平に伸ばし、反対の手で体に引き寄せます",
    keyPoints: [
      "肘を伸ばしたまま胸の前へ",
      "肩の後面に伸びを感じる",
      "肩をすくめないように注意",
    ],
  },
  {
    id: "chest-stretch",
    name: "胸郭ストレッチ",
    nameEn: "Chest Stretch",
    target: "大胸筋・小胸筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "ドア枠に両腕を当て、体を前に踏み出して胸を開きます",
    keyPoints: [
      "肘を肩の高さで90度に曲げる",
      "体を前に出して胸を開く",
      "胸の前面に伸びを感じたらキープ",
    ],
  },
  {
    id: "neck-lateral-stretch",
    name: "頸部側屈ストレッチ",
    nameEn: "Neck Lateral Flexion Stretch",
    target: "僧帽筋上部・斜角筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 15,
    description:
      "椅子に座り、片手で頭を横に倒して首の側面を伸ばします",
    keyPoints: [
      "反対の肩を下げて固定する",
      "頭を倒す力は軽く（自重程度）",
      "首の横に伸びを感じたらキープ",
    ],
  },
  {
    id: "neck-rotation-stretch",
    name: "頸部回旋ストレッチ",
    nameEn: "Neck Rotation Stretch",
    target: "胸鎖乳突筋・斜角筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 15,
    description:
      "椅子に座り、頭をゆっくり横に回して首の回旋筋を伸ばします",
    keyPoints: [
      "顎を引いたまま回旋する",
      "無理に回しすぎない",
      "痛みのない範囲でゆっくり行う",
    ],
  },
  {
    id: "cat-stretch",
    name: "背部ストレッチ（キャットストレッチ）",
    nameEn: "Cat Stretch",
    target: "脊柱起立筋・多裂筋",
    posture: "四つ這い",
    category: "ストレッチ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "四つ這いで背中を天井に向かって丸め、おへそを覗き込むようにします",
    keyPoints: [
      "息を吐きながら背中を丸める",
      "おへそを覗き込むイメージ",
      "ゆっくり元に戻す",
    ],
  },
  {
    id: "lateral-trunk-stretch",
    name: "体側ストレッチ",
    nameEn: "Lateral Trunk Stretch",
    target: "腹斜筋・広背筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "体幹",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "椅子に座り、片腕を頭上に挙げて反対側に上体を倒します",
    keyPoints: [
      "お尻が浮かないようにする",
      "体側に伸びを感じたらキープ",
      "呼吸を止めずに行う",
    ],
  },
  {
    id: "forearm-stretch",
    name: "前腕ストレッチ",
    nameEn: "Forearm Stretch",
    target: "前腕伸筋群",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "片腕を前に伸ばし、反対の手で指先を手前に引いて前腕を伸ばします",
    keyPoints: [
      "肘をしっかり伸ばしたまま行う",
      "前腕の外側に伸びを感じる",
      "痛みが出ない程度にゆっくり引く",
    ],
  },
  // ── Batch 4: バランス・ADL系 ──
  {
    id: "single-leg-stand",
    name: "片脚立位",
    nameEn: "Single Leg Stand",
    target: "バランス",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 15,
    description:
      "壁の近くで片脚を床から浮かせ、反対の脚でバランスを保ちます",
    keyPoints: [
      "必ず壁や椅子の近くで行う",
      "ふらつく場合は手を添える",
      "視線は正面のやや下を見る",
    ],
  },
  {
    id: "step-reaction",
    name: "ステップ反応訓練",
    nameEn: "Step Reaction Training",
    target: "バランス・反応能力",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "立位から素早く一歩踏み出す練習をします（前・横・後ろ）",
    keyPoints: [
      "素早く一歩踏み出して止まる",
      "前・横・後ろの各方向で練習",
      "転倒に注意し安全な環境で行う",
    ],
  },
  {
    id: "weight-shift-ap",
    name: "重心移動訓練（前後）",
    nameEn: "Weight Shift Anteroposterior",
    target: "バランス・体幹",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "足を肩幅に開いて立ち、体を前後にゆっくり傾けて重心を移動します",
    keyPoints: [
      "足の裏で重心の位置を感じる",
      "つま先側・踵側に交互に移動",
      "壁の近くで安全に行う",
    ],
  },
  {
    id: "weight-shift-lr",
    name: "重心移動訓練（左右）",
    nameEn: "Weight Shift Lateral",
    target: "バランス・中殿筋",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "足を肩幅より広く開いて立ち、体を左右にゆっくり傾けて重心を移動します",
    keyPoints: [
      "左右の足に交互に体重を乗せる",
      "体幹はまっすぐに保つ",
      "ゆっくり大きく動かす",
    ],
  },
  {
    id: "dynamic-reach",
    name: "動的バランス（リーチ訓練）",
    nameEn: "Dynamic Reach",
    target: "バランス・体幹",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 5,
    defaultSets: 2,
    description:
      "片脚立ちで手を前方に伸ばし、動的なバランスを鍛えます",
    keyPoints: [
      "支持脚の膝を軽く曲げる",
      "できるだけ遠くにリーチする",
      "ふらつく場合は壁の近くで行う",
    ],
  },
  {
    id: "unstable-balance",
    name: "不安定面バランス",
    nameEn: "Unstable Surface Balance",
    target: "バランス・足関節周囲筋",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "バランスパッドやクッションの上に立ち、バランスを保ちます",
    keyPoints: [
      "必ず壁や椅子の近くで行う",
      "最初は両足、慣れたら片足で",
      "視線は正面を見てバランスを取る",
    ],
  },
  {
    id: "gait-forward",
    name: "歩行訓練（前進）",
    nameEn: "Forward Gait Training",
    target: "歩行能力・下肢全般",
    posture: "立位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 1,
    defaultSets: 3,
    description:
      "正しいフォームを意識しながらゆっくり歩きます",
    keyPoints: [
      "踵から接地してつま先で蹴り出す",
      "腕を自然に振る",
      "視線は前方を見る",
    ],
  },
  {
    id: "gait-backward",
    name: "歩行訓練（後退）",
    nameEn: "Backward Gait Training",
    target: "バランス・大殿筋",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 1,
    defaultSets: 3,
    description:
      "壁や手すりの近くで、後ろ向きにゆっくり歩きます",
    keyPoints: [
      "つま先から接地する",
      "手すりや壁に手を添えて安全に",
      "視線は前方を向いたまま",
    ],
  },
  {
    id: "sit-to-stand",
    name: "立ち上がり訓練",
    nameEn: "Sit to Stand",
    target: "大腿四頭筋・大殿筋",
    posture: "座位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子から手を使わずに立ち上がる練習をします",
    keyPoints: [
      "体を前に倒してから立ち上がる",
      "膝に手をつくのはOK",
      "ゆっくり座り、勢いをつけない",
    ],
  },
  {
    id: "chair-stand",
    name: "椅子からの立ち座り",
    nameEn: "Chair Stand",
    target: "大腿四頭筋・大殿筋",
    posture: "座位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "両手を胸の前で交差し、椅子から立ったり座ったりを繰り返します",
    keyPoints: [
      "手を使わずに立ち座りする",
      "ドスンと座らずゆっくり腰を降ろす",
      "膝が内側に入らないようにする",
    ],
  },
  {
    id: "step-up-advanced",
    name: "段差昇降（応用）",
    nameEn: "Advanced Step-Up",
    target: "大腿四頭筋・大殿筋",
    posture: "立位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "手すりを使わず、やや高めの段差を昇り降りします",
    keyPoints: [
      "慣れるまでは壁に手を添えてもよい",
      "膝がつま先より前に出すぎない",
      "ゆっくり降りる（着地を柔らかく）",
    ],
  },
  {
    id: "turning",
    name: "方向転換訓練",
    nameEn: "Turning Training",
    target: "バランス・体幹",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 5,
    defaultSets: 2,
    description:
      "立った状態から90度・180度の方向転換をゆっくり練習します",
    keyPoints: [
      "小さなステップで回る",
      "足を交差させない",
      "ふらつく場合は壁の近くで行う",
    ],
  },
  {
    id: "floor-to-stand",
    name: "床からの立ち上がり",
    nameEn: "Floor to Stand",
    target: "全身・ADL",
    posture: "臥位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    description:
      "床に座った状態から椅子などを支えに立ち上がる練習をします",
    keyPoints: [
      "まず片膝立ちになる",
      "椅子や台を手で支えて立ち上がる",
      "転倒に注意し安全な環境で行う",
    ],
  },
  {
    id: "reach-training",
    name: "リーチ動作訓練",
    nameEn: "Reach Training",
    target: "バランス・体幹",
    posture: "座位",
    category: "ADL",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、手を前方や上方に伸ばして物に手を届かせる練習をします",
    keyPoints: [
      "体幹を使って手を伸ばす",
      "無理のない範囲で遠くまで伸ばす",
      "お尻が椅子から浮かないようにする",
    ],
  },
  {
    id: "object-transfer",
    name: "物品移動訓練",
    nameEn: "Object Transfer Training",
    target: "上肢・体幹・ADL",
    posture: "立位",
    category: "ADL",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "テーブル上の物を持ち上げて別の場所に移す練習をします",
    keyPoints: [
      "軽い物から始める",
      "体幹を安定させて行う",
      "左右の手で交互に行う",
    ],
  },
  {
    id: "dressing-training",
    name: "着衣動作訓練",
    nameEn: "Dressing Training",
    target: "柔軟性・ADL",
    posture: "座位",
    category: "ADL",
    bodyPart: "下肢",
    defaultReps: 5,
    defaultSets: 2,
    description:
      "椅子に座って靴下の着脱など、着衣に必要な動作を練習します",
    keyPoints: [
      "足を膝の上に乗せて行う",
      "背中を丸めすぎない",
      "息を止めずにゆっくり行う",
    ],
  },
  // ── Batch 5: 上肢・体幹・呼吸 ──
  {
    id: "shoulder-internal-rotation",
    name: "肩関節内旋運動",
    nameEn: "Shoulder Internal Rotation",
    target: "肩甲下筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "脇を締めて肘を90度に曲げ、セラバンドを持って手を内側に引きます",
    keyPoints: [
      "脇をしっかり締めたまま行う",
      "肘の位置を動かさない",
      "ゆっくり戻す（戻す時も筋力を使う）",
    ],
  },
  {
    id: "scapular-elevation",
    name: "肩甲骨挙上運動",
    nameEn: "Scapular Elevation",
    target: "僧帽筋上部・肩甲挙筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "椅子に座り、両肩を耳に近づけるようにすくめます",
    keyPoints: [
      "肩をできるだけ高く上げる",
      "5秒キープしてゆっくり下ろす",
      "首に力が入りすぎないように注意",
    ],
  },
  {
    id: "scapular-depression",
    name: "肩甲骨下制運動",
    nameEn: "Scapular Depression",
    target: "僧帽筋下部・広背筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "椅子に座り、両肩を下方向にグッと押し下げます",
    keyPoints: [
      "肩を耳から遠ざけるイメージ",
      "5秒キープしてゆっくり戻す",
      "背筋を伸ばして行う",
    ],
  },
  {
    id: "wrist-extension",
    name: "手関節背屈運動",
    nameEn: "Wrist Extension",
    target: "前腕伸筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "腕を前に伸ばし、手首を上に反らす運動をします",
    keyPoints: [
      "肘をしっかり伸ばしたまま行う",
      "ゆっくり上げてゆっくり下ろす",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "wrist-flexion",
    name: "手関節掌屈運動",
    nameEn: "Wrist Flexion",
    target: "前腕屈筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "腕を前に伸ばし、手首を下に曲げる運動をします",
    keyPoints: [
      "肘をしっかり伸ばしたまま行う",
      "ゆっくり曲げてゆっくり戻す",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "forearm-pronation-supination",
    name: "前腕回内・回外運動",
    nameEn: "Forearm Pronation/Supination",
    target: "回内筋・回外筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "肘を90度に曲げて脇を締め、手のひらを上下に返す運動をします",
    keyPoints: [
      "肘の位置を動かさない",
      "手のひらを上向き・下向きに交互に",
      "ゆっくり大きく回す",
    ],
  },
  {
    id: "elbow-flexion",
    name: "肘関節屈曲運動",
    nameEn: "Elbow Flexion",
    target: "上腕二頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、軽いダンベルを持って肘を曲げ伸ばしします",
    keyPoints: [
      "肘の位置を体の横に固定する",
      "ゆっくり上げてゆっくり下ろす",
      "反動を使わない",
    ],
  },
  {
    id: "elbow-extension",
    name: "肘関節伸展運動",
    nameEn: "Elbow Extension",
    target: "上腕三頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、腕を頭上に挙げて肘の曲げ伸ばしをします",
    keyPoints: [
      "反対の手で肘を支える",
      "ゆっくり伸ばしてゆっくり戻す",
      "肘の位置を動かさない",
    ],
  },
  {
    id: "finger-opposition",
    name: "手指対立運動",
    nameEn: "Finger Opposition",
    target: "母指対立筋・手内筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 3,
    description:
      "親指の先を各指の先に順番につける運動をします",
    keyPoints: [
      "人差し指から小指まで順番に",
      "しっかり指先同士をつける",
      "できるだけ速く正確に行う",
    ],
  },
  {
    id: "finger-extension",
    name: "手指伸展運動",
    nameEn: "Finger Extension",
    target: "指伸筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 15,
    defaultSets: 3,
    description:
      "輪ゴムを全ての指にかけて、指を大きく開く運動をします",
    keyPoints: [
      "指を大きくしっかり開く",
      "ゆっくり開いてゆっくり戻す",
      "輪ゴムの強さを調整する",
    ],
  },
  {
    id: "side-plank",
    name: "サイドプランク",
    nameEn: "Side Plank",
    target: "腹斜筋・中殿筋",
    posture: "側臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 15,
    description:
      "横向きで前腕と足の側面で体を支え、一直線を保ちます",
    keyPoints: [
      "肘は肩の真下に置く",
      "腰が落ちないようにする",
      "呼吸を止めずにキープ",
    ],
  },
  {
    id: "dead-bug",
    name: "デッドバグ",
    nameEn: "Dead Bug",
    target: "腹横筋・腹直筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "仰向けで対側の手と脚を同時にまっすぐ伸ばし、体幹を安定させます",
    keyPoints: [
      "腰が床から浮かないようにする",
      "対側の手足をゆっくり伸ばす",
      "息を吐きながら伸ばす",
    ],
  },
  {
    id: "pelvic-tilt",
    name: "ペルビックティルト",
    nameEn: "Pelvic Tilt",
    target: "腹横筋・骨盤底筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "仰向けで腰を床に押しつけるように骨盤を後傾させます",
    keyPoints: [
      "腰と床の隙間をなくすイメージ",
      "5秒キープしてゆっくり戻す",
      "お腹に軽く力を入れる",
    ],
  },
  {
    id: "cat-cow",
    name: "キャット&カウ",
    nameEn: "Cat & Cow",
    target: "脊柱起立筋・腹筋群",
    posture: "四つ這い",
    category: "ストレッチ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "四つ這いで背中を丸める（キャット）と反らす（カウ）を交互に行います",
    keyPoints: [
      "息を吐きながら背中を丸める",
      "息を吸いながら背中を反らす",
      "ゆっくり大きく動かす",
    ],
  },
  {
    id: "back-extension",
    name: "背筋運動（バックエクステンション）",
    nameEn: "Back Extension",
    target: "脊柱起立筋",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "うつ伏せで上体をゆっくり持ち上げます",
    keyPoints: [
      "腰を反りすぎない",
      "おへそは床につけたまま",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "abdominal-breathing",
    name: "腹式呼吸",
    nameEn: "Abdominal Breathing",
    target: "横隔膜・腹横筋",
    posture: "臥位",
    category: "呼吸",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "仰向けでお腹に手を当て、お腹を膨らませるように鼻から息を吸います",
    keyPoints: [
      "鼻から吸ってお腹を膨らませる",
      "口からゆっくり吐いてお腹を凹ませる",
      "胸はできるだけ動かさない",
    ],
  },
  {
    id: "pursed-lip-breathing",
    name: "口すぼめ呼吸",
    nameEn: "Pursed Lip Breathing",
    target: "呼吸筋",
    posture: "座位",
    category: "呼吸",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "鼻から吸い、口をすぼめてゆっくり長く息を吐きます",
    keyPoints: [
      "鼻から2秒吸う",
      "口をすぼめて4〜6秒かけて吐く",
      "吐く時間を吸う時間の2倍以上に",
    ],
  },
  {
    id: "thoracic-expansion",
    name: "胸郭拡張訓練",
    nameEn: "Thoracic Expansion",
    target: "肋間筋・呼吸補助筋",
    posture: "座位",
    category: "呼吸",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "両手を胸の横に当て、肋骨を広げるように深く息を吸います",
    keyPoints: [
      "手で肋骨の動きを感じる",
      "胸を横に広げるイメージで吸う",
      "ゆっくり吐いて肋骨を戻す",
    ],
  },
  {
    id: "deep-breathing",
    name: "深呼吸訓練",
    nameEn: "Deep Breathing",
    target: "呼吸筋全般",
    posture: "座位",
    category: "呼吸",
    bodyPart: "体幹",
    defaultReps: 5,
    defaultSets: 3,
    description:
      "両腕を広げながら深く息を吸い、腕を戻しながらゆっくり吐きます",
    keyPoints: [
      "腕を広げながら大きく吸う",
      "腕を戻しながらゆっくり吐く",
      "背筋を伸ばして行う",
    ],
  },
  // ── Batch 6: 運動療法応用 ──
  {
    id: "knee-flexion-rom",
    name: "膝関節屈曲ROM訓練",
    nameEn: "Knee Flexion ROM",
    target: "膝関節周囲筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、踵を滑らせて膝の曲げ伸ばしをします",
    keyPoints: [
      "踵の下にタオルを敷くと滑りやすい",
      "痛みのない範囲でゆっくり曲げる",
      "曲げたところで数秒キープ",
    ],
  },
  {
    id: "knee-extension-rom",
    name: "膝関節伸展ROM訓練",
    nameEn: "Knee Extension ROM",
    target: "膝関節周囲筋",
    posture: "臥位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "仰向けで踵の下にタオルを置き、膝裏を床に押しつけるように伸ばします",
    keyPoints: [
      "膝裏を床に近づけるイメージ",
      "10秒キープしてゆっくり戻す",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "williams-exercise",
    name: "ウィリアムス体操",
    nameEn: "Williams Flexion Exercise",
    target: "腰椎屈曲・腰部筋群",
    posture: "臥位",
    category: "ストレッチ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "仰向けで両膝を抱えて胸に引き寄せ、腰を丸めます",
    keyPoints: [
      "両手で膝を抱えて胸に引き寄せる",
      "腰が丸まるのを感じたらキープ",
      "腰椎ヘルニアの方は医師に相談",
    ],
  },
  {
    id: "mckenzie-exercise",
    name: "マッケンジー体操",
    nameEn: "McKenzie Extension Exercise",
    target: "腰椎伸展・脊柱起立筋",
    posture: "臥位",
    category: "ストレッチ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "うつ伏せで両手で上体を押し上げ、腰を反らします",
    keyPoints: [
      "腰から下は床につけたまま",
      "腕の力で上体を押し上げる",
      "痛みが出たら無理をしない",
    ],
  },
  {
    id: "pelvic-floor",
    name: "骨盤底筋運動",
    nameEn: "Pelvic Floor Exercise",
    target: "骨盤底筋群",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "体幹",
    defaultReps: 10,
    defaultSets: 3,
    defaultHoldSeconds: 5,
    description:
      "仰向けで骨盤底筋を締める（尿を止めるイメージ）運動をします",
    keyPoints: [
      "お尻の穴を締めるイメージ",
      "5秒キープしてゆっくり緩める",
      "お腹や太ももに力を入れすぎない",
    ],
  },
  {
    id: "upper-reach",
    name: "上肢リーチ訓練",
    nameEn: "Upper Limb Reach Training",
    target: "上肢・体幹",
    posture: "座位",
    category: "ADL",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "椅子に座り、手を斜め上方に伸ばして体幹の回旋とリーチを練習します",
    keyPoints: [
      "できるだけ遠くに手を伸ばす",
      "体幹を回旋させて伸ばす",
      "お尻が椅子から浮かないようにする",
    ],
  },
  {
    id: "fine-motor",
    name: "手指巧緻運動",
    nameEn: "Fine Motor Exercise",
    target: "手内筋・指屈筋群",
    posture: "座位",
    category: "ADL",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "小さな物をつまんで移す練習をします（ビー玉、ボタン等）",
    keyPoints: [
      "指先でしっかりつまむ",
      "左右の手で交互に行う",
      "できるだけ速く正確に",
    ],
  },
  {
    id: "weight-bearing",
    name: "下肢荷重訓練",
    nameEn: "Lower Limb Weight Bearing",
    target: "下肢全般",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "体重計に片脚を乗せ、徐々に体重をかける練習をします",
    keyPoints: [
      "平行棒や壁を支えにする",
      "医師の指示した荷重量を守る",
      "痛みが出たら荷重を減らす",
    ],
  },
  {
    id: "codman-exercise",
    name: "コッドマン体操",
    nameEn: "Codman Exercise",
    target: "肩関節周囲筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "体を前に倒し、腕を振り子のように円を描いて揺らします",
    keyPoints: [
      "腕の力を抜いてだらんと垂らす",
      "体の揺れで腕を動かす",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "wand-exercise",
    name: "ワンド体操",
    nameEn: "Wand Exercise",
    target: "肩関節周囲筋",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "棒を両手で持ち、頭の上に持ち上げて肩の可動域を広げます",
    keyPoints: [
      "健側の手で患側を補助する",
      "痛みのない範囲で持ち上げる",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "wall-climbing",
    name: "壁登り運動",
    nameEn: "Wall Climbing Exercise",
    target: "肩関節周囲筋",
    posture: "立位",
    category: "ストレッチ",
    bodyPart: "上肢",
    defaultReps: 5,
    defaultSets: 2,
    description:
      "壁に向かって立ち、指で壁を登るように腕を挙げていきます",
    keyPoints: [
      "指先で壁を少しずつ登る",
      "到達点をマークして目標にする",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "hip-abduction-training",
    name: "股関節外転訓練",
    nameEn: "Hip Abduction Training",
    target: "中殿筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁に手を添えて立ち、脚を横方向に持ち上げます",
    keyPoints: [
      "骨盤を水平に保つ",
      "体が傾かないようにする",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "hip-flexion-training",
    name: "股関節屈曲訓練",
    nameEn: "Hip Flexion Training",
    target: "腸腰筋・大腿直筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁に手を添えて立ち、膝を曲げて太ももを持ち上げます",
    keyPoints: [
      "背筋をまっすぐ保つ",
      "太ももが水平になるまで上げる",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "step-balance",
    name: "ステップバランス",
    nameEn: "Step Balance",
    target: "バランス・下肢全般",
    posture: "立位",
    category: "バランス",
    bodyPart: "下肢",
    defaultReps: 5,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "踏み台に片脚で昇り、そのまま片脚立位を保ちます",
    keyPoints: [
      "壁の近くで安全に行う",
      "昇った脚で片脚立位をキープ",
      "ゆっくり降りる",
    ],
  },
  {
    id: "quad-setting-advanced",
    name: "大腿四頭筋セッティング応用",
    nameEn: "Advanced Quad Setting",
    target: "大腿四頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "足首に重錘をつけて、椅子に座り膝を伸ばして持ち上げます",
    keyPoints: [
      "重錘は軽い物から始める",
      "5秒キープしてゆっくり下ろす",
      "膝に痛みがある場合は中止する",
    ],
  },
  // ── Batch 7: 100種到達 ──
  {
    id: "hip-extension",
    name: "股関節伸展運動",
    nameEn: "Hip Extension",
    target: "大殿筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁や椅子に手を添えて立ち、脚をまっすぐ後方に持ち上げます",
    keyPoints: [
      "体が前に傾かないようにする",
      "お尻に力が入ることを確認",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "ankle-dorsiflexion",
    name: "足関節背屈運動",
    nameEn: "Ankle Dorsiflexion",
    target: "前脛骨筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "椅子に座り、つま先を天井に向かって持ち上げます",
    keyPoints: [
      "踵は床につけたまま",
      "つま先をできるだけ高く上げる",
      "ゆっくり上げてゆっくり下ろす",
    ],
  },
  {
    id: "ankle-plantarflexion",
    name: "足関節底屈運動",
    nameEn: "Ankle Plantarflexion",
    target: "下腿三頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "椅子に座り、つま先を床に向かって伸ばします",
    keyPoints: [
      "足首をしっかり伸ばす",
      "ゆっくり伸ばしてゆっくり戻す",
      "ふくらはぎに力が入ることを確認",
    ],
  },
  {
    id: "toe-raise",
    name: "つま先上げ運動",
    nameEn: "Toe Raise",
    target: "前脛骨筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 15,
    defaultSets: 2,
    description:
      "壁に手を添えて立ち、踵を床につけたままつま先を持ち上げます",
    keyPoints: [
      "体はまっすぐに保つ",
      "つま先をできるだけ高く上げる",
      "カーフレイズと交互に行うと効果的",
    ],
  },
  {
    id: "hip-ir-stretch",
    name: "股関節内旋ストレッチ",
    nameEn: "Hip Internal Rotation Stretch",
    target: "外旋筋群",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "椅子に座り、膝を内側に倒して股関節の内旋を伸ばします",
    keyPoints: [
      "痛みのない範囲で行う",
      "お尻が浮かないようにする",
      "伸びを感じたら20秒キープ",
    ],
  },
  {
    id: "towel-gather",
    name: "タオルギャザー",
    nameEn: "Towel Gather",
    target: "足趾屈筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 3,
    description:
      "椅子に座り、足指でタオルを掴んで手繰り寄せます",
    keyPoints: [
      "足指をしっかり曲げてタオルを掴む",
      "左右の足で交互に行う",
      "扁平足の予防にも効果的",
    ],
  },
  {
    id: "adductor-stretch",
    name: "内転筋ストレッチ",
    nameEn: "Adductor Stretch",
    target: "内転筋群",
    posture: "座位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 3,
    defaultSets: 2,
    defaultHoldSeconds: 20,
    description:
      "椅子に座って両脚を大きく開き、上体を前に倒して内ももを伸ばします",
    keyPoints: [
      "背中を丸めずに股関節から倒す",
      "内ももに伸びを感じたらキープ",
      "痛みのない範囲で行う",
    ],
  },
  {
    id: "seated-march",
    name: "座位での足踏み",
    nameEn: "Seated March",
    target: "腸腰筋・大腿四頭筋",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 20,
    defaultSets: 2,
    description:
      "椅子に座り、膝を交互に持ち上げて足踏みをします",
    keyPoints: [
      "背筋を伸ばして行う",
      "膝をできるだけ高く上げる",
      "リズムよく交互に行う",
    ],
  },
  {
    id: "shoulder-shrug",
    name: "肩すくめ運動",
    nameEn: "Shoulder Shrug",
    target: "僧帽筋上部",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "ダンベルを持って立ち、両肩を耳に向かってすくめます",
    keyPoints: [
      "肩をできるだけ高く上げる",
      "3秒キープしてゆっくり下ろす",
      "軽いダンベルから始める",
    ],
  },
  {
    id: "chin-tuck",
    name: "顎引き運動",
    nameEn: "Chin Tuck",
    target: "深頸屈筋群",
    posture: "座位",
    category: "筋トレ",
    bodyPart: "上肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 5,
    description:
      "椅子に座り、顎を喉に向かって引く運動をします",
    keyPoints: [
      "二重あごを作るイメージ",
      "5秒キープしてゆっくり戻す",
      "頭は前後に動かさず顎だけ引く",
    ],
  },
  {
    id: "single-leg-calf-raise",
    name: "片脚カーフレイズ",
    nameEn: "Single Leg Calf Raise",
    target: "下腿三頭筋",
    posture: "立位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    description:
      "壁に手を添え、片脚でつま先立ちになります",
    keyPoints: [
      "踵をできるだけ高く上げる",
      "ゆっくり上げてゆっくり下ろす",
      "両脚カーフレイズに慣れてから行う",
    ],
  },
  {
    id: "supine-hip-flexion",
    name: "仰臥位股関節屈曲運動",
    nameEn: "Supine Hip Flexion",
    target: "腸腰筋・大腿直筋",
    posture: "臥位",
    category: "ストレッチ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 10,
    description:
      "仰向けで片膝を抱えて胸に引き寄せます",
    keyPoints: [
      "反対の脚はまっすぐ伸ばす",
      "腰が浮かないようにする",
      "伸びを感じたら10秒キープ",
    ],
  },
  {
    id: "prone-hip-extension",
    name: "腹臥位股関節伸展運動",
    nameEn: "Prone Hip Extension",
    target: "大殿筋・ハムストリングス",
    posture: "臥位",
    category: "筋トレ",
    bodyPart: "下肢",
    defaultReps: 10,
    defaultSets: 2,
    defaultHoldSeconds: 3,
    description:
      "うつ伏せで片脚を膝を伸ばしたまま天井に向かって持ち上げます",
    keyPoints: [
      "骨盤が浮かないようにする",
      "お尻に力が入ることを確認",
      "3秒キープしてゆっくり下ろす",
    ],
  },
];
