export const ILLUSTRATIONS: Record<string, number> = {
  "patella-setting": require("../../assets/illustrations/patella-setting.webp"),
  slr: require("../../assets/illustrations/slr.webp"),
  bridge: require("../../assets/illustrations/bridge.webp"),
  clamshell: require("../../assets/illustrations/clamshell.webp"),
  squat: require("../../assets/illustrations/squat.webp"),
  "calf-raise": require("../../assets/illustrations/calf-raise.webp"),
  "draw-in": require("../../assets/illustrations/draw-in.webp"),
  "seated-knee-ext": require("../../assets/illustrations/seated-knee-ext.webp"),
  "scapular-retraction": require("../../assets/illustrations/scapular-retraction.webp"),
  "wall-pushup": require("../../assets/illustrations/wall-pushup.webp"),
  "bird-dog": require("../../assets/illustrations/bird-dog.webp"),
  plank: require("../../assets/illustrations/plank.webp"),
  "sit-up": require("../../assets/illustrations/sit-up.webp"),
  "trunk-rotation": require("../../assets/illustrations/trunk-rotation.webp"),
  "shoulder-flexion": require("../../assets/illustrations/shoulder-flexion.webp"),
  "shoulder-abduction": require("../../assets/illustrations/shoulder-abduction.webp"),
  "shoulder-external-rotation": require("../../assets/illustrations/shoulder-external-rotation.webp"),
  "hand-grip": require("../../assets/illustrations/hand-grip.webp"),
  "hip-abduction": require("../../assets/illustrations/hip-abduction.webp"),
  "hamstring-curl": require("../../assets/illustrations/hamstring-curl.webp"),
  "tandem-stance": require("../../assets/illustrations/tandem-stance.webp"),
  "step-up": require("../../assets/illustrations/step-up.webp"),
};
