export const ILLUSTRATIONS: Record<string, number> = {
  "patella-setting": require("../../assets/illustrations/patella-setting.png"),
  slr: require("../../assets/illustrations/slr.png"),
  bridge: require("../../assets/illustrations/bridge.png"),
  clamshell: require("../../assets/illustrations/clamshell.png"),
  squat: require("../../assets/illustrations/squat.png"),
  "calf-raise": require("../../assets/illustrations/calf-raise.png"),
  "draw-in": require("../../assets/illustrations/draw-in.png"),
  "seated-knee-ext": require("../../assets/illustrations/seated-knee-ext.png"),
  "scapular-retraction": require("../../assets/illustrations/scapular-retraction.png"),
  "wall-pushup": require("../../assets/illustrations/wall-pushup.png"),
  "bird-dog": require("../../assets/illustrations/bird-dog.png"),
  plank: require("../../assets/illustrations/plank.png"),
  "sit-up": require("../../assets/illustrations/sit-up.png"),
  "trunk-rotation": require("../../assets/illustrations/trunk-rotation.png"),
  "shoulder-flexion": require("../../assets/illustrations/shoulder-flexion.png"),
  "shoulder-abduction": require("../../assets/illustrations/shoulder-abduction.png"),
  "shoulder-external-rotation": require("../../assets/illustrations/shoulder-external-rotation.png"),
  "hand-grip": require("../../assets/illustrations/hand-grip.png"),
  "hip-abduction": require("../../assets/illustrations/hip-abduction.png"),
  "hamstring-curl": require("../../assets/illustrations/hamstring-curl.png"),
  "tandem-stance": require("../../assets/illustrations/tandem-stance.png"),
  "step-up": require("../../assets/illustrations/step-up.png"),
};
