export const ILLUSTRATIONS: Record<string, number> = {
  "patella-setting": require("../../assets/illustrations/patella-setting.webp"),
  slr: require("../../assets/illustrations/slr.webp"),
  bridge: require("../../assets/illustrations/bridge.webp"),
  clamshell: require("../../assets/illustrations/clamshell.webp"),
  squat: require("../../assets/illustrations/squat.webp"),
  "calf-raise": require("../../assets/illustrations/calf-raise.webp"),
  "draw-in": require("../../assets/illustrations/draw-in.webp"),
  "seated-knee-ext": require("../../assets/illustrations/seated-knee-ext.webp"),
  "scapular-retraction": require("../../assets/illustrations/scapular-retraction.webp"),
  "wall-pushup": require("../../assets/illustrations/wall-pushup.webp"),
  "bird-dog": require("../../assets/illustrations/bird-dog.webp"),
  plank: require("../../assets/illustrations/plank.webp"),
  "sit-up": require("../../assets/illustrations/sit-up.webp"),
  "trunk-rotation": require("../../assets/illustrations/trunk-rotation.webp"),
  "shoulder-flexion": require("../../assets/illustrations/shoulder-flexion.webp"),
  "shoulder-abduction": require("../../assets/illustrations/shoulder-abduction.webp"),
  "shoulder-external-rotation": require("../../assets/illustrations/shoulder-external-rotation.webp"),
  "hand-grip": require("../../assets/illustrations/hand-grip.webp"),
  "hip-abduction": require("../../assets/illustrations/hip-abduction.webp"),
  "hamstring-curl": require("../../assets/illustrations/hamstring-curl.webp"),
  "tandem-stance": require("../../assets/illustrations/tandem-stance.webp"),
  "step-up": require("../../assets/illustrations/step-up.webp"),
  "hamstring-stretch": require("../../assets/illustrations/hamstring-stretch.webp"),
  "quad-stretch": require("../../assets/illustrations/quad-stretch.webp"),
  "calf-stretch": require("../../assets/illustrations/calf-stretch.webp"),
  "hip-flexor-stretch": require("../../assets/illustrations/hip-flexor-stretch.webp"),
  "piriformis-stretch": require("../../assets/illustrations/piriformis-stretch.webp"),
  "itb-stretch": require("../../assets/illustrations/itb-stretch.webp"),
  "shoulder-flexion-stretch": require("../../assets/illustrations/shoulder-flexion-stretch.webp"),
  "shoulder-er-stretch": require("../../assets/illustrations/shoulder-er-stretch.webp"),
  "shoulder-ha-stretch": require("../../assets/illustrations/shoulder-ha-stretch.webp"),
  "chest-stretch": require("../../assets/illustrations/chest-stretch.webp"),
  "neck-lateral-stretch": require("../../assets/illustrations/neck-lateral-stretch.webp"),
  "neck-rotation-stretch": require("../../assets/illustrations/neck-rotation-stretch.webp"),
  "cat-stretch": require("../../assets/illustrations/cat-stretch.webp"),
  "lateral-trunk-stretch": require("../../assets/illustrations/lateral-trunk-stretch.webp"),
  "forearm-stretch": require("../../assets/illustrations/forearm-stretch.webp"),
  "single-leg-stand": require("../../assets/illustrations/single-leg-stand.webp"),
  "step-reaction": require("../../assets/illustrations/step-reaction.webp"),
  "weight-shift-ap": require("../../assets/illustrations/weight-shift-ap.webp"),
  "weight-shift-lr": require("../../assets/illustrations/weight-shift-lr.webp"),
  "dynamic-reach": require("../../assets/illustrations/dynamic-reach.webp"),
  "unstable-balance": require("../../assets/illustrations/unstable-balance.webp"),
  "gait-forward": require("../../assets/illustrations/gait-forward.webp"),
  "gait-backward": require("../../assets/illustrations/gait-backward.webp"),
  "sit-to-stand": require("../../assets/illustrations/sit-to-stand.webp"),
  "chair-stand": require("../../assets/illustrations/chair-stand.webp"),
  "step-up-advanced": require("../../assets/illustrations/step-up-advanced.webp"),
  "turning": require("../../assets/illustrations/turning.webp"),
  "floor-to-stand": require("../../assets/illustrations/floor-to-stand.webp"),
  "reach-training": require("../../assets/illustrations/reach-training.webp"),
  "object-transfer": require("../../assets/illustrations/object-transfer.webp"),
  "dressing-training": require("../../assets/illustrations/dressing-training.webp"),
  "shoulder-internal-rotation": require("../../assets/illustrations/shoulder-internal-rotation.webp"),
  "scapular-elevation": require("../../assets/illustrations/scapular-elevation.webp"),
  "scapular-depression": require("../../assets/illustrations/scapular-depression.webp"),
  "wrist-extension": require("../../assets/illustrations/wrist-extension.webp"),
  "wrist-flexion": require("../../assets/illustrations/wrist-flexion.webp"),
  "forearm-pronation-supination": require("../../assets/illustrations/forearm-pronation-supination.webp"),
  "elbow-flexion": require("../../assets/illustrations/elbow-flexion.webp"),
  "elbow-extension": require("../../assets/illustrations/elbow-extension.webp"),
  "finger-opposition": require("../../assets/illustrations/finger-opposition.webp"),
  "finger-extension": require("../../assets/illustrations/finger-extension.webp"),
  "side-plank": require("../../assets/illustrations/side-plank.webp"),
  "dead-bug": require("../../assets/illustrations/dead-bug.webp"),
  "pelvic-tilt": require("../../assets/illustrations/pelvic-tilt.webp"),
  "cat-cow": require("../../assets/illustrations/cat-cow.webp"),
  "back-extension": require("../../assets/illustrations/back-extension.webp"),
  "abdominal-breathing": require("../../assets/illustrations/abdominal-breathing.webp"),
  "pursed-lip-breathing": require("../../assets/illustrations/pursed-lip-breathing.webp"),
  "thoracic-expansion": require("../../assets/illustrations/thoracic-expansion.webp"),
  "deep-breathing": require("../../assets/illustrations/deep-breathing.webp"),
  "knee-flexion-rom": require("../../assets/illustrations/knee-flexion-rom.webp"),
  "knee-extension-rom": require("../../assets/illustrations/knee-extension-rom.webp"),
  "williams-exercise": require("../../assets/illustrations/williams-exercise.webp"),
  "mckenzie-exercise": require("../../assets/illustrations/mckenzie-exercise.webp"),
  "pelvic-floor": require("../../assets/illustrations/pelvic-floor.webp"),
  "upper-reach": require("../../assets/illustrations/upper-reach.webp"),
  "fine-motor": require("../../assets/illustrations/fine-motor.webp"),
  "weight-bearing": require("../../assets/illustrations/weight-bearing.webp"),
  "codman-exercise": require("../../assets/illustrations/codman-exercise.webp"),
  "wand-exercise": require("../../assets/illustrations/wand-exercise.webp"),
  "wall-climbing": require("../../assets/illustrations/wall-climbing.webp"),
  "hip-abduction-training": require("../../assets/illustrations/hip-abduction-training.webp"),
  "hip-flexion-training": require("../../assets/illustrations/hip-flexion-training.webp"),
  "step-balance": require("../../assets/illustrations/step-balance.webp"),
  "quad-setting-advanced": require("../../assets/illustrations/quad-setting-advanced.webp"),
  "hip-extension": require("../../assets/illustrations/hip-extension.webp"),
  "ankle-dorsiflexion": require("../../assets/illustrations/ankle-dorsiflexion.webp"),
  "ankle-plantarflexion": require("../../assets/illustrations/ankle-plantarflexion.webp"),
  "toe-raise": require("../../assets/illustrations/toe-raise.webp"),
  "hip-ir-stretch": require("../../assets/illustrations/hip-ir-stretch.webp"),
  "towel-gather": require("../../assets/illustrations/towel-gather.webp"),
  "adductor-stretch": require("../../assets/illustrations/adductor-stretch.webp"),
  "seated-march": require("../../assets/illustrations/seated-march.webp"),
  "shoulder-shrug": require("../../assets/illustrations/shoulder-shrug.webp"),
  "chin-tuck": require("../../assets/illustrations/chin-tuck.webp"),
  "single-leg-calf-raise": require("../../assets/illustrations/single-leg-calf-raise.webp"),
  "supine-hip-flexion": require("../../assets/illustrations/supine-hip-flexion.webp"),
  "prone-hip-extension": require("../../assets/illustrations/prone-hip-extension.webp"),
};

/**
 * 開始姿勢のイラスト（2枚化）。
 *
 * 運動を「開始姿勢 → 動作中」の2枚で示すための1枚目。
 * ILLUSTRATIONS 側が「動作中」にあたる。
 *
 * ここに登録がない運動は従来どおり1枚（動作中のみ）で表示される。
 * 生成が進むたびに追記する運用（require は静的パスが必要なため自動生成できない）。
 *
 * 追加手順:
 *   1. assets/illustrations/{id}-start.webp を配置
 *   2. 下に `"{id}": require("../../assets/illustrations/{id}-start.webp"),` を追記
 *
 * 生成プロンプト: scripts/batch8-start-frames.md
 */
export const START_ILLUSTRATIONS: Record<string, number> = {
  // Batch 8（頻用30種）。生成が完了した運動から順に追記する
  "adductor-stretch": require("../../assets/illustrations/adductor-stretch-start.webp"),
  "ankle-dorsiflexion": require("../../assets/illustrations/ankle-dorsiflexion-start.webp"),
  "back-extension": require("../../assets/illustrations/back-extension-start.webp"),
  "bird-dog": require("../../assets/illustrations/bird-dog-start.webp"),
  "bridge": require("../../assets/illustrations/bridge-start.webp"),
  "calf-raise": require("../../assets/illustrations/calf-raise-start.webp"),
  "calf-stretch": require("../../assets/illustrations/calf-stretch-start.webp"),
  "chin-tuck": require("../../assets/illustrations/chin-tuck-start.webp"),
  "clamshell": require("../../assets/illustrations/clamshell-start.webp"),
  "draw-in": require("../../assets/illustrations/draw-in-start.webp"),
  "hamstring-stretch": require("../../assets/illustrations/hamstring-stretch-start.webp"),
  "hip-abduction": require("../../assets/illustrations/hip-abduction-start.webp"),
  "hip-abduction-training": require("../../assets/illustrations/hip-abduction-training-start.webp"),
  "hip-extension": require("../../assets/illustrations/hip-extension-start.webp"),
  "patella-setting": require("../../assets/illustrations/patella-setting-start.webp"),
  "pelvic-tilt": require("../../assets/illustrations/pelvic-tilt-start.webp"),
  "quad-stretch": require("../../assets/illustrations/quad-stretch-start.webp"),
  "scapular-retraction": require("../../assets/illustrations/scapular-retraction-start.webp"),
  "seated-knee-ext": require("../../assets/illustrations/seated-knee-ext-start.webp"),
  "seated-march": require("../../assets/illustrations/seated-march-start.webp"),
  "shoulder-flexion": require("../../assets/illustrations/shoulder-flexion-start.webp"),
  "single-leg-stand": require("../../assets/illustrations/single-leg-stand-start.webp"),
  "sit-to-stand": require("../../assets/illustrations/sit-to-stand-start.webp"),
  "slr": require("../../assets/illustrations/slr-start.webp"),
  "squat": require("../../assets/illustrations/squat-start.webp"),
  "step-up": require("../../assets/illustrations/step-up-start.webp"),
  "tandem-stance": require("../../assets/illustrations/tandem-stance-start.webp"),
  "toe-raise": require("../../assets/illustrations/toe-raise-start.webp"),
  "towel-gather": require("../../assets/illustrations/towel-gather-start.webp"),
  "weight-shift-lr": require("../../assets/illustrations/weight-shift-lr-start.webp"),
};

/** 2枚化されているか（開始姿勢の登録があるか） */
export const hasStartFrame = (exerciseId: string): boolean =>
  START_ILLUSTRATIONS[exerciseId] !== undefined;
